version: '3.8'

services:
  # LARAVEL SERVICE
  laravel-app:
    build: 
      context: ./laravel-presensi
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:E9VCTwp7mNqf35A4BpIzI9V445+HmZAcxA3zCR37xGI=
      - APP_DEBUG=true
      - APP_URL=https://api.texere.studio
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=sikawan
      - DB_USERNAME=postgres
      - DB_PASSWORD=sikawan_password
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - AI_SERVICE_URL=http://ai.texere.studio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sikawan-laravel.rule=Host(`sikawan.texere.studio`)"
      - "traefik.http.routers.sikawan-laravel.entrypoints=websecure"
      - "traefik.http.routers.sikawan-laravel.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - sikawan_network
      - traefik_proxy
    depends_on:
      - database

  # PYTHON AI SERVICE
  ai-service:
    build: 
      context: ./skripsi-presensi-ai
    ports:
      - "8088:8088"
    volumes:
      - ./skripsi-presensi-ai/models:/app/models
      - ./skripsi-presensi-ai/dataset:/app/dataset
      - ./skripsi-presensi-ai/storage:/app/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sikawan-ai.rule=Host(`ai.texere.studio`)"
      - "traefik.http.routers.sikawan-ai.entrypoints=websecure"
      - "traefik.http.routers.sikawan-ai.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - sikawan_network
      - traefik_proxy

  # WATCHTOWER AUTO-UPDATES
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    command: --label-enable --cleanup --interval 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sikawan_network

  # DATABASE POSTGRES
  database:
    build:
      context: ./docker/postgres
    image: sikawan-postgres-postgis:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sikawan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sikawan_password
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - sikawan_network

networks:
  sikawan_network:
    external: false
  traefik_proxy:
    external: true

volumes:
  pg-data: